### ISSUE TITLE
Add buffer filter

### ISSUE THREAD

**Issue by EpsilonKu** [nanozuki/tabby.nvim#86]
Bufferline.nvim ([docs](https://github.com/akinsho/bufferline.nvim/blob/83bf4dc7bff642e145c8b4547aa596803a8b4dc4/doc/bufferline.txt#L441)) has filter option. Also it filter when you navigate between buffers (because of custom :BufferLineCycleNext command). 
I know it's easy to make it. But I think it will really useful to make ready custom command and filter. I personally use it for nvim-dap (it create repl as buffer).

**Comment by nanozuki** [comment]
Sorry for the delay in my response due to the holidays. I think this feature is very useful just I haven't figured out a way to implement it yet. Thanks for the other plugins you provided for my reference.

I will reply to this issue on the progress of developing this feature.

In the current case, you can also use normal lua code to filter. Just return the empty string in the callback of `line.wins().foreach({callback})` and the label of the win will not be rendered.

**Comment by nanozuki** [comment]
I want to add filters in `line.wins({filters}).foreach({callback})`, for example: 
Users can define customer filters like:

```lua
function not_nvimtree(win)
  return not string.find(win.name(), "NvimTree")
end
```

```lua
line.wins(not_nvimtree).foreach(function
...
end)
```

What do you think about it?

**Comment by EpsilonKu** [comment]
Yeah, sounds really cool. Better than bufferline.nvim.

**Comment by ajtakrajta** [comment]
I'm wondering if such buffer filtering would allow to keep separate sets of buffers per tab, like it's possible with vim-ctrlspace. I do not use splits, only set of buffers in each tab. I always see just one buffer in a tab, but I can easily cycle thru the tab's buffers.

**Comment by nanozuki** [comment]
@EpsilonKu I complete this feature now. You can check the doc in [tabby.line.wins().foreach()](https://github.com/nanozuki/tabby.nvim/blob/main/doc/tabby.txt#L243). Welcome to feedback on this issue!

**Comment by nanozuki** [comment]
> 

This filter feature only changes the display in the tabline. Won't change the behavior in opening a buffer. Maybe you can add a customer command or something else to do this.
