### ISSUE TITLE
Add option to choose truncate mode

### ISSUE THREAD

**Issue by edshamis** [nanozuki/tabby.nvim#93]
Thanks for the great plugin, really enjoy it.

Currently when the screen width is too short the tabline is truncated on the left side, hiding the tabs. I would prefer to truncate the windows list instead. Is it possible? If not, can it be added?
A more global solutions, I'm thinking about, would be giving each tabline chunk some truncation priority field.
What do you think?

**Comment by nanozuki** [comment]
Oh, yes, I think this is a necessary improvement. Recently I read the doc. Nvim/Vim has a truncate point to control where to truncate the tabline. But I didn't use it before, I must do some tests and trials. 

For now, "tabby.nvim" use the nvim native tabline option to render the tabline. Since that the priority field has seemed hard to implement, depending on the behavior of "truncate point",

**Comment by edshamis** [comment]
Nice. Is it possible for now at least disable windows list completely if
and when width isn't sufficient?

**Comment by nanozuki** [comment]
If you use presets config, you can choose the `tab_only` presets.

**Comment by nanozuki** [comment]
I add a function [line.truncate_point()](https://github.com/nanozuki/tabby.nvim/blob/main/doc/tabby.txt#L292) to add a truncate point. You can add it before the window labels, such as:

```lua
    line.spacer(),
    line.truncate_point(),
    line.wins_in_tab(line.api.get_current_tab()).foreach(function(win)
      return {
         -- window label
      }
    end),

```

**Comment by edshamis** [comment]
Thanks!. I ended up with tabs only, I like this simple look.
